version: '3.9'

services:
  auth-service:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        APP_NAME: auth-service
    environment:
      REPOSITORY_CONNECTION_STRING: mongodb://root:password@mongo:27017
      KAFKA_PRODUCER_BROKERS: kafka
      KAFKA_PRODUCER_TOPIC: some-topic

    ports:
      - 8080:8080
    depends_on:
      - mongo
      - kafka

  mongo: # NOTE: Databases should only be edited in `./containers/db/mongo/*.js`
    image: mongo:5.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mongo
    ports:
      - 27017:27017
    healthcheck:
      test: [ "CMD", "mongo", "--eval", 'db.runCommand("ping").ok', "localhost:27017/test", "--quiet" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    volumes:
      - ./containers/db/mongo:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express
    ports:
      - 27018:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    depends_on:
      mongo:
        condition: service_healthy # NOTE: Wait for `mongo`
