###############################################

### Create task
POST http://localhost:2401/api/task
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMjkzMDVmZGEtOGJlZi0wNTUwLTk2ZDEtYjllNDFlMWUzMmNmIiwiZW1haWwiOiJtaXNoa2EiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2OTI1MTgxMjJ9.bYuypteOe6R6_wx8cc3RFcsBoL2tBAGAg35w8E4BdSY
Content-Type: application/json

{
  "name": "task1",
  "description": "go and do that"
}

### Reassign tasks
PATCH http://localhost:2401/admin/tasks/reassign
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pc2hrYSIsImVtYWlsIjoibUBzaC5rYSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY5MTgzOTI5MX0.hCfgT55c9JzMJFjUtunmB-JSS0EF6o9_HOmk0uCD0pw


### Get user's tasks
GET http://localhost:2401/api/tasks/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pc2hrYSIsImVtYWlsIjoibUBzaC5rYSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY5MTgzOTI5MX0.hCfgT55c9JzMJFjUtunmB-JSS0EF6o9_HOmk0uCD0pw

### Close task
PATCH http://localhost:2401/api/task
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pc2hrYSIsImVtYWlsIjoibUBzaC5rYSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY5MTgzOTI5MX0.hCfgT55c9JzMJFjUtunmB-JSS0EF6o9_HOmk0uCD0pw
Content-Type: application/json

{
  "task_id": "17456117-3cae-1529-5ebb-ae8cc0bb4c45"
}

### Delete task (only admins)
DELETE http://localhost:2401/admin/task
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pc2hrYSIsImVtYWlsIjoibUBzaC5rYSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY5MTgzOTI5MX0.hCfgT55c9JzMJFjUtunmB-JSS0EF6o9_HOmk0uCD0pw
Content-Type: application/json

{
    "task_id": "17456117-3cae-1529-5ebb-ae8cc0bb4c45"
}
